# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spg < Formula
  desc ""
  homepage "https://github.com/nekinci/spg"
  version "1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nekinci/spg/releases/download/v1.0/spg_1.0_darwin_arm64.tar.gz"
      sha256 "d8272c21c978b5a779762715e3ceb96d1523f8d545df9bd5b16493cf2659dd4d"

      def install
        bin.install "spg"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nekinci/spg/releases/download/v1.0/spg_1.0_darwin_amd64.tar.gz"
      sha256 "551e8717d58620a5f16eda0b7455d20f03e212cef914f96ba19a3a6724565d82"

      def install
        bin.install "spg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nekinci/spg/releases/download/v1.0/spg_1.0_linux_amd64.tar.gz"
      sha256 "9e832e8cb7a6950e3f126745bad9796e9019667d7ce451cd44f5dad60996ccfd"

      def install
        bin.install "spg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nekinci/spg/releases/download/v1.0/spg_1.0_linux_arm64.tar.gz"
      sha256 "5d7fee612b9195bd61e141c81d359c347ffd298a6a5f0f673c988fa796eb5e18"

      def install
        bin.install "spg"
      end
    end
  end
end
