# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spg < Formula
  desc ""
  homepage "https://github.com/nekinci/spg"
  version "1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nekinci/spg/releases/download/v1.0/spg_1.0_darwin_amd64.tar.gz"
      sha256 "7242834bd1494401615a8ddff8dd980e9c8de61d3334c78cf8bff613491c94e4"

      def install
        bin.install "spg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nekinci/spg/releases/download/v1.0/spg_1.0_darwin_arm64.tar.gz"
      sha256 "0273fa6d9b8061a9ecfecdbd7625a8b9718ef670c679cd433ec36b5acf57fea6"

      def install
        bin.install "spg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nekinci/spg/releases/download/v1.0/spg_1.0_linux_amd64.tar.gz"
      sha256 "2275a315111ff47826d28e5640ff775e7145dff5d7aa6fcf39ed900056146b80"

      def install
        bin.install "spg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nekinci/spg/releases/download/v1.0/spg_1.0_linux_arm64.tar.gz"
      sha256 "77d135a840b3782a196a0ac254535172777a9730264dad4f17055bead8dad8a5"

      def install
        bin.install "spg"
      end
    end
  end
end
