# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spg < Formula
  desc ""
  homepage "https://github.com/nekinci/spg"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nekinci/spg/releases/download/v1.0.0/spg_1.0.0_darwin_arm64.tar.gz"
      sha256 "ba5957bf137250759730f18eeacb1401d33a4cb3cf4d84fddf8de1fc06f9737d"

      def install
        bin.install "spg"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nekinci/spg/releases/download/v1.0.0/spg_1.0.0_darwin_amd64.tar.gz"
      sha256 "e8f2c946163ec9da7e3358713babf563a44bc1868f1bb45de2037993449dcb39"

      def install
        bin.install "spg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nekinci/spg/releases/download/v1.0.0/spg_1.0.0_linux_amd64.tar.gz"
      sha256 "4c1b397eae50febb9a6b3f7adab2eb521e43258eb25ae74bb0517818cf407d63"

      def install
        bin.install "spg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nekinci/spg/releases/download/v1.0.0/spg_1.0.0_linux_arm64.tar.gz"
      sha256 "49742404e9fb73072d88df3cbe6e1da5736fdff4131aa475d37acaeddee281f8"

      def install
        bin.install "spg"
      end
    end
  end
end
